version: '1'

services:
    postgres:
        image: postgres
        ports: 
            - "5432:5432"
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=mysecretpassword
            - POSTGRES_DB=postgres
    golang:
        #image: aincicau/golang:1.0
        build: .
        restart: on-failure
        environment: 
            - DATABASE_URL=postgres://postgres:mysecretpassword@golangorm_postgres_1:5432/postgres?sslmode=disable
        ports: 
            - "8080:8080"  
        depends_on:
            - postgres
            #://POSTGRES_USER:POSTGRES_PASSWORD@numeproiect_serviciu(postgres)_versiune:port/POSTGRES_DB?sslmode=disable